"""wstępna migration

Revision ID: f698b8585896
Revises: 
Create Date: 2021-01-29 14:14:00.777198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f698b8585896'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'numerrej')
    op.drop_column('users', 'imie')
    op.drop_column('users', 'psswrd')
    op.drop_column('users', 'nazwisko')
    op.drop_column('users', 'email')
    op.drop_column('users', 'nrtelefonu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nrtelefonu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', mysql.TEXT(collation='utf32_polish_ci'), nullable=False))
    op.add_column('users', sa.Column('nazwisko', mysql.TEXT(collation='utf32_polish_ci'), nullable=False))
    op.add_column('users', sa.Column('psswrd', mysql.TEXT(collation='utf32_polish_ci'), nullable=False))
    op.add_column('users', sa.Column('imie', mysql.TEXT(collation='utf32_polish_ci'), nullable=False))
    op.add_column('users', sa.Column('numerrej', mysql.TEXT(collation='utf32_polish_ci'), nullable=False))
    # ### end Alembic commands ###
